name: Maven Build

on:
  push:          # bei jedem Push ausführen
  pull_request:  # zusätzlich bei Pull Requests prüfen

jobs:
  build:
    name: Build and Test with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 25 (Oracle)
        uses: actions/setup-java@v4
        with:
          distribution: oracle
          java-version: '25'
          cache: maven

      - name: Verify Maven Wrapper or Install Maven
        run: |
          if [ -f "./mvnw" ]; then
            echo "Maven Wrapper gefunden"
            chmod +x mvnw
          else
            echo "Kein Maven Wrapper gefunden, benutze System-Maven"
          fi

      - name: Build with Maven
        run: |
          if [ -f "./mvnw" ]; then
            ./mvnw -
