name: Java Build

on:
  push:
    branches:
      - '**'   # Bei jedem Push auf alle Branches
  pull_request:
    branches:
      - '**'   # Bei jedem PR auf alle Branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -B
